# Generated by Django 3.2.5 on 2021-07-23 21:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pressao',
            options={'verbose_name': 'Pressão', 'verbose_name_plural': 'Pressões'},
        ),
        migrations.AlterField(
            model_name='pressao',
            name='data',
            field=models.DateTimeField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='pressao',
            name='dia',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='Diastólica'),
        ),
        migrations.AlterField(
            model_name='pressao',
            name='pul',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(150)], verbose_name='Pulso'),
        ),
        migrations.AlterField(
            model_name='pressao',
            name='sis',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)], verbose_name='Sistólica'),
        ),
    ]
