# Generated by Django 3.2.5 on 2021-07-23 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_auto_20210723_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressao',
            name='pul',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(150)], verbose_name='Pulso'),
        ),
    ]
